name = "InferenceTargets"
uuid = "c783b089-9926-4030-92a9-5158851e9169"
authors = ["Alexandre Bouchard"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
